spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=track_logistics
    username: postgres
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL10Dialect

  flyway:
    locations: "classpath:db.migration"
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    driverClassName: org.postgresql.Driver
    defaultSchema: track_logistics



springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html